# Generated by Django 3.1.12 on 2024-11-16 07:04

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20241115_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switchname', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='id',
        ),
        migrations.AddField(
            model_name='user_details',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mac_address',
            field=djongo.models.fields.JSONField(),
        ),
    ]
