# Generated by Django 5.1.3 on 2024-11-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20241116_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='mac_address',
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
