# Generated by Django 5.1.3 on 2024-11-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename__id_user_details_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='register',
        ),
    ]
