# Generated by Django 3.1.12 on 2024-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_details_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddress', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=24)),
                ('wifi_name', models.CharField(max_length=255)),
                ('wifi_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
