# Generated by Django 3.2.25 on 2024-12-02 07:20

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_user_id_register__id_alter_switch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='_id',
        ),
        migrations.AddField(
            model_name='register',
            name='user_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='register',
            table='user_register',
        ),
    ]
